### PR TITLE
Update FCVerticalMenu.m

### PR DESCRIPTION
**Pull request by jeffreyjackson**
The button shouldn't maintain selected after release.

### CODE REVIEW

**Comment by jeffreyjackson** [comment]
Hi @filippocamillo - just wanted to make sure you saw this!

**Comment by filippocamillo** [comment]
Hi @jeffreyjackson! Sorry, I completely missed it. I'm not sure this is the right behavior. I mean, the button status is like a tabBar button, it maintain the state and give a context to the user. Maybe it could be better to make it configurable? What do you think?

Thanks!

**Comment by jeffreyjackson** [comment]
yeah that would work for me!

**Comment by jeffreyjackson** [comment]
I'm using it in http://entourage.io - a new update coming soon also.

**Comment by jeffreyjackson** [comment]
thanks man this is great

**Comment by filippocamillo** [comment]
Just almost one year later... sorry about that!
How is going your app Entourage?

F

Filippo Camillo
{iOS Developer & Digital Creative}

w. http://filippocamillo.com
m. +39 3403395387

2016-02-14 20:22 GMT+01:00 Jeffrey Jackson notifications@github.com:

**Pull request merged**
